# Define Java linter: PMD
java_binary(
    name = "pmd",
    main_class = "net.sourceforge.pmd.PMD",
    #main_class = "net.sourceforge.pmd.cli.PmdCli",
    runtime_deps = ["@net_sourceforge_pmd"],
)
